# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 23:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ofsite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='to_user',
        ),
        migrations.AddField(
            model_name='friend',
            name='friends',
            field=models.ManyToManyField(related_name='_friend_friends_+', to='ofsite.Friend'),
        ),
        migrations.AddField(
            model_name='friend',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friendship', to=settings.AUTH_USER_MODEL),
        ),
    ]
