# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 02:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ofsite', '0004_comments_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='comments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ofsite.Comments'),
        ),
    ]
