# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofsite', '0005_auto_20170325_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
