# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 03:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ofsite', '0009_auto_20170325_0301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='message',
            new_name='msg',
        ),
    ]
