# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofsite', '0010_auto_20170325_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='msg',
            field=models.TextField(),
        ),
    ]
