# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 21:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ofsite', '0012_posts_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='title',
        ),
    ]
